### PR TITLE
Update docs for v1.0.2 release

### PR DESCRIPTION
**Pull request by luckyj5**
Update docs for tile v1.0.2 release: 
- includes support for PAS 2.4.
- updated stemcell to Ubuntu Xenial.
- updated advanced config section for added config param.

### CODE REVIEW

**Comment by jknostman3** [comment]
@luckyj5 Thanks!

**Comment by luckyj5** [comment]
Thanks @jknostman3. 
Just realized that the release date is set to Feb 27, it needs to be March 1. Should I create another PR for that?

**Comment by jncd** [comment]
Hi @luckyj5 and @jknostman3 
I just updated the date to march 1 on both index and release notes pages.

**Comment by jknostman3** [comment]
@jncd I was able to make the release on the 27th so I changed it back

**Pull request merged**
