### PR TITLE
Update troubleshooting section for Splunk nozzle

### PR DESCRIPTION
**Pull request by luckyj5**
Added few basic failure scenarios and their resolution to enhance troubleshooting section in the docs.

### CODE REVIEW

**Comment by jknostman3** [comment]
@luckyj5 Thanks!

**Comment by jknostman3** [comment]
@luckyj5 I made some edits to ensure that the common errors section of the installing page makes more sense from a format perspective. I made the assumption that the text following the log results of the errors wasn't presented in the actual log but was rather the troubleshooting way to fix the error. Please let me know if that was incorrect. Thanks!

**Comment by luckyj5** [comment]
@jknostman3 Yes, you made the correct assumption and it looks much better after your edits. 
Thank you!

**Comment by jknostman3** [comment]
@luckyj5 Perfect. No problem and thanks for the clarification!

**Comment by luckyj5** [comment]
@jknostman3 Just checked this link - https://docs.pivotal.io/partners/splunk/troubleshooting.html
Looks like this section is at 2 places - "To view the nozzle’s logs running on PCF do the following:"
We only need this section under "Troubleshooting Walkthrough" section. 
Should I create another PR to remove it?

**Comment by jknostman3** [comment]
@luckyj5 Yes please! Good catch

**Comment by luckyj5** [comment]
@jknostman3  Just created a PR for that -  https://github.com/pivotal-cf/docs-splunk/pull/15 
Please let me know if anything. 
Thanks!

**Pull request merged**
